// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package database

import (
	"context"
)

const getPermissionsName = `-- name: GetPermissionsName :one
SELECT id, name FROM permissions
`

func (q *Queries) GetPermissionsName(ctx context.Context) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionsName)
	var i Permission
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
