// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: general.sql

package database

import (
	"context"
)

const resetAddress = `-- name: ResetAddress :exec
DELETE FROM user_address
`

func (q *Queries) ResetAddress(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetAddress)
	return err
}

const resetCart = `-- name: ResetCart :exec
DELETE FROM cart
`

func (q *Queries) ResetCart(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetCart)
	return err
}

const resetMedicines = `-- name: ResetMedicines :exec
DELETE FROM medicines
`

func (q *Queries) ResetMedicines(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetMedicines)
	return err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetUsers)
	return err
}
