name: mediTrust

services:
    postgres-local:
        image: postgres:17.5-alpine3.21
        container_name: postgres-local
        environment:
            - POSTGRES_DB=${DBNAME}
            - POSTGRES_USER=${DBUSER}
            - POSTGRES_PASSWORD=${DBPASS}
        ports:
            - "${DBPORT}:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: