// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package cartDB

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type CartItem struct {
	ID         int32
	CartID     pgtype.UUID
	MedicineID pgtype.UUID
	Quantity   int32
	Price      int32
	CreatedAt  pgtype.Timestamp
}

type Medicine struct {
	ID           pgtype.UUID
	Name         string
	Dosage       string
	Description  string
	Manufacturer string
	Price        int32
	Stock        int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
