openapi: 3.0.0

info:
    title: Medicine API
    description: API for managing medicines in an online pharmacy
    version: 0.0.1
    license:
        name: MIT
    x-oapi-codegen-middlewares:
        - Middlewares
    x-oapi-codegen-type-mappings:
        uuid: github.com/google/uuid.UUID

servers:
    - url: http://localhost:8080/api/v1

# security:
#     # - access_token: [ ]
#     - BearerAuth: []

paths:

    /medicines:

        # POST /api/v1/medicines
        post:
            summary: Create a new medicine (admin only)
            description: Create a new medicine entry. Only an admin can perform this action.
            operationId: createMedicine
            tags:
                - medicine
            security:
                - BearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/MedicineRequest'
            responses:
                "201":
                    description: Medicine created successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MedicineResponse'
                "400":
                    $ref: '#/components/responses/BadRequestError'
                "500":
                    $ref: '#/components/responses/InternalServerError'


        # GET /api/v1/medicines
        get:
            summary: Get all medicines
            description: Fetch a list of available medicines
            operationId: fetchMedicineList
            tags:
                - medicines
            responses:
                "200":
                    description: List of medicines
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/MedicineResponse'
                "500":
                    $ref: '#/components/responses/InternalServerError'


    /medicines/{medicineID}:

        # GET /api/v1/medicines/{medicineID}
        get:
            summary: Get a medicine by ID
            description: Fetch information of a medicine using ID
            operationId: FetchMedicineByID
            tags:
                - medicines
            parameters:
                - $ref: '#/components/parameters/MedicineID'
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MedicineResponse'
                "404":
                    $ref: '#/components/responses/NotFoundError'
                "500":
                    $ref: '#/components/responses/InternalServerError'

        # PUT /api/v1/medicines/{medicineID}
        put:
            summary: Update a medicine by ID (admin only)
            description: Update information of a medicine by its ID
            operationId: updateMedicineInfoByID
            tags:
                - medicines
            security:
                - BearerAuth: [ ]
            parameters:
                - $ref: '#/components/parameters/MedicineID'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/MedicineRequest'
            responses:
                "202":
                    description: medicine updated successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MedicineResponse'
                "400":
                    $ref: '#/components/responses/BadRequestError'
                "404":
                    $ref: '#/components/responses/NotFoundError'
                "500":
                    $ref: '#/components/responses/InternalServerError'


        # DELETE /api/v1/medicines/{medicineID}
        delete:
            summary: Delete a medicine by ID (admin only)
            description: remove a medicine from the store
            operationId: deleteMedicineByID
            tags:
                - medicines
            security:
                - BearerAuth: [ ]
            parameters:
                - $ref: '#/components/parameters/MedicineID'
            responses:
                "204":
                    description: Medicine deleted successfully
                "400":
                    $ref: '#/components/responses/BadRequestError'
                "500":
                    $ref: '#/components/responses/InternalServerError'

components:
    parameters:
        MedicineID:
            name: medicineID
            in: path
            required: true
            schema:
                type: string
                format: googleuuid
                x-go-type: googleuuid.UUID
                x-go-type-import:
                        path: github.com/google/uuid
                        name: googleuuid

    responses:
        InternalServerError:
            description: Internal server error

        BadRequestError:
            description: Bad request, invalid input

        NotFoundError:
            description: Not Found

    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

        # access_token:
        #     type: apiKey
        #     in: header
        #     name: Authorization


    schemas:

        MedicineRequest:
            type: object
            x-go-type: medicineRequest
            x-go-type-import:
                path: github.com/Dhar01/internal/product/model
                name: model
            properties:
                name:
                    type: string
                    example: 'Losectil'
                manufacturer:
                    type: string
                    example: 'Eskayef Pharmaceuticals Ltd.'
                dosage:
                    type: string
                    example: '20mg'
                description:
                    type: string
                    example: 'Used in treatment of gastric ulcers'
                price:
                    type: integer
                    format: int32
                    example: 5
                    x-oapi-codegen-extra-tags:
                    validate: "required,gte=0"
                stock:
                    type: integer
                    format: int32
                    example: 10
                    x-oapi-codegen-extra-tags:
                        validate: "required,gte=0"

        MedicineResponse:
            type: object
            x-go-type: medicineResponse
            x-go-type-import:
                path: github.com/Dhar01/internal/product/model
                name: model
            properties:
                id:
                    type: string
                    format: uuid
                    example: '550e8400-e29b-41d4-a716-446655440000'
                name:
                    type: string
                    example: 'Losectil'
                manufacturer:
                    type: string
                    example: 'Eskayef Pharmaceuticals Ltd.'
                dosage:
                    type: string
                    example: '20mg'
                description:
                    type: string
                    example: 'Used in treatment of gastric ulcers'
                price:
                    type: integer
                    format: int32
                    example: 5
                stock:
                    type: integer
                    format: int32
                    example: 10
                createdAt:
                    type: string
                    format: date-time
                    example: '2025-05-09T12:00:00Z'
                updatedAt:
                    type: string
                    format: date-time
                    example: '2025-05-09T12:30:00Z'