// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package medicineDb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Medicine struct {
	ID           uuid.UUID
	Name         string
	Dosage       string
	Description  string
	Manufacturer string
	Price        int32
	Stock        int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
