// Package user_gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package user_gen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	googleuuid "github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Address defines model for Address.
type Address struct {
	City          *string `json:"city,omitempty"`
	Country       *string `json:"country,omitempty"`
	PostalCode    *string `json:"postal_code,omitempty"`
	StreetAddress *string `json:"street_address,omitempty"`
}

// Error500Problem defines model for Error500Problem.
type Error500Problem struct {
	Message *string `json:"message,omitempty"`
	Status  *int32  `json:"status,omitempty"`
}

// FetchUserInfoResponse defines model for FetchUserInfoResponse.
type FetchUserInfoResponse struct {
	Address  *Address             `json:"address,omitempty"`
	Age      *int32               `json:"age,omitempty" validate:"gte=18"`
	Email    *openapi_types.Email `json:"email,omitempty"`
	IsActive *bool                `json:"is_active,omitempty"`
	Name     *FullName            `json:"name,omitempty"`
	Phone    *string              `json:"phone,omitempty"`
	Role     *string              `json:"role,omitempty"`
}

// FullName defines model for FullName.
type FullName struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Address *Address  `json:"address,omitempty"`
	Age     *int32    `json:"age,omitempty" validate:"gte=18"`
	Name    *FullName `json:"name,omitempty"`
	Phone   *string   `json:"phone,omitempty"`
}

// UpdateUserResponse defines model for UpdateUserResponse.
type UpdateUserResponse struct {
	Address  Address             `json:"address"`
	Age      int32               `json:"age" validate:"gte=18"`
	Email    openapi_types.Email `json:"email"`
	IsActive bool                `json:"is_active"`
	Name     FullName            `json:"name"`
	Phone    string              `json:"phone"`
	Role     string              `json:"role"`
}

// User defines model for User.
type User struct {
	Address      *Address             `json:"address,omitempty"`
	Age          *int32               `json:"age,omitempty" validate:"gte=18"`
	Email        *openapi_types.Email `json:"email,omitempty"`
	HashPassword *string              `json:"hashPassword,omitempty"`
	Id           *googleuuid.UUID     `json:"id,omitempty"`
	IsActive     *bool                `json:"is_active,omitempty"`
	Name         *FullName            `json:"name,omitempty"`
	Phone        *string              `json:"phone,omitempty"`
	Role         *string              `json:"role,omitempty"`
}

// UserID defines model for UserID.
type UserID = googleuuid.UUID

// UpdateUserInfoByIDJSONRequestBody defines body for UpdateUserInfoByID for application/json ContentType.
type UpdateUserInfoByIDJSONRequestBody = UpdateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete user data
	// (DELETE /users/{userID})
	DeleteUserByID(ctx echo.Context, userID UserID) error
	// Get user using userID
	// (GET /users/{userID})
	FetchUserInfoByID(ctx echo.Context, userID UserID) error
	// Update a user information using userID
	// (PUT /users/{userID})
	UpdateUserInfoByID(ctx echo.Context, userID UserID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteUserByID converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userID" -------------
	var userID UserID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserByID(ctx, userID)
	return err
}

// FetchUserInfoByID converts echo context to params.
func (w *ServerInterfaceWrapper) FetchUserInfoByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userID" -------------
	var userID UserID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FetchUserInfoByID(ctx, userID)
	return err
}

// UpdateUserInfoByID converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserInfoByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userID" -------------
	var userID UserID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserInfoByID(ctx, userID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/users/:userID", wrapper.DeleteUserByID)
	router.GET(baseURL+"/users/:userID", wrapper.FetchUserInfoByID)
	router.PUT(baseURL+"/users/:userID", wrapper.UpdateUserInfoByID)

}

type BadRequestErrorResponse struct {
}

type InternalServerErrorResponse struct {
}

type NotFoundErrorResponse struct {
}

type UnauthorizedAccessErrorResponse struct {
}

type DeleteUserByIDRequestObject struct {
	UserID UserID `json:"userID"`
}

type DeleteUserByIDResponseObject interface {
	VisitDeleteUserByIDResponse(w http.ResponseWriter) error
}

type DeleteUserByID204Response struct {
}

func (response DeleteUserByID204Response) VisitDeleteUserByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteUserByID401Response = UnauthorizedAccessErrorResponse

func (response DeleteUserByID401Response) VisitDeleteUserByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type FetchUserInfoByIDRequestObject struct {
	UserID UserID `json:"userID"`
}

type FetchUserInfoByIDResponseObject interface {
	VisitFetchUserInfoByIDResponse(w http.ResponseWriter) error
}

type FetchUserInfoByID200JSONResponse FetchUserInfoResponse

func (response FetchUserInfoByID200JSONResponse) VisitFetchUserInfoByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FetchUserInfoByID400Response = BadRequestErrorResponse

func (response FetchUserInfoByID400Response) VisitFetchUserInfoByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type FetchUserInfoByID404Response = NotFoundErrorResponse

func (response FetchUserInfoByID404Response) VisitFetchUserInfoByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type FetchUserInfoByID500Response = InternalServerErrorResponse

func (response FetchUserInfoByID500Response) VisitFetchUserInfoByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type UpdateUserInfoByIDRequestObject struct {
	UserID UserID `json:"userID"`
	Body   *UpdateUserInfoByIDJSONRequestBody
}

type UpdateUserInfoByIDResponseObject interface {
	VisitUpdateUserInfoByIDResponse(w http.ResponseWriter) error
}

type UpdateUserInfoByID202JSONResponse UpdateUserResponse

func (response UpdateUserInfoByID202JSONResponse) VisitUpdateUserInfoByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserInfoByID400Response = BadRequestErrorResponse

func (response UpdateUserInfoByID400Response) VisitUpdateUserInfoByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateUserInfoByID401Response = UnauthorizedAccessErrorResponse

func (response UpdateUserInfoByID401Response) VisitUpdateUserInfoByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateUserInfoByID500Response = InternalServerErrorResponse

func (response UpdateUserInfoByID500Response) VisitUpdateUserInfoByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Delete user data
	// (DELETE /users/{userID})
	DeleteUserByID(ctx context.Context, request DeleteUserByIDRequestObject) (DeleteUserByIDResponseObject, error)
	// Get user using userID
	// (GET /users/{userID})
	FetchUserInfoByID(ctx context.Context, request FetchUserInfoByIDRequestObject) (FetchUserInfoByIDResponseObject, error)
	// Update a user information using userID
	// (PUT /users/{userID})
	UpdateUserInfoByID(ctx context.Context, request UpdateUserInfoByIDRequestObject) (UpdateUserInfoByIDResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// DeleteUserByID operation middleware
func (sh *strictHandler) DeleteUserByID(ctx echo.Context, userID UserID) error {
	var request DeleteUserByIDRequestObject

	request.UserID = userID

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUserByID(ctx.Request().Context(), request.(DeleteUserByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUserByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteUserByIDResponseObject); ok {
		return validResponse.VisitDeleteUserByIDResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// FetchUserInfoByID operation middleware
func (sh *strictHandler) FetchUserInfoByID(ctx echo.Context, userID UserID) error {
	var request FetchUserInfoByIDRequestObject

	request.UserID = userID

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FetchUserInfoByID(ctx.Request().Context(), request.(FetchUserInfoByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FetchUserInfoByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(FetchUserInfoByIDResponseObject); ok {
		return validResponse.VisitFetchUserInfoByIDResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUserInfoByID operation middleware
func (sh *strictHandler) UpdateUserInfoByID(ctx echo.Context, userID UserID) error {
	var request UpdateUserInfoByIDRequestObject

	request.UserID = userID

	var body UpdateUserInfoByIDJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserInfoByID(ctx.Request().Context(), request.(UpdateUserInfoByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserInfoByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserInfoByIDResponseObject); ok {
		return validResponse.VisitUpdateUserInfoByIDResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYYW/bNhP+KwLffJQt2bHT1MALLEHmLm1TBE2DfQiC4CKdJbYUqZLHNG6g/z6QUmzZ",
	"kpsO7YqtW77EEu/I5+557szzA0tUUSqJkgybPbASNBRIqP3TpUF9euI+cclmrATKWcgkFMhmzNaLIdP4",
	"0XKNKZuRthgyk+RYgPNaKF0AsRnLlMoEWstTFjJals7fkOYyYyG7H2Rq0LxcGw4vL/3uq9UBL0qlye3b",
	"INjY1YObsYxTbm+HiSqiejny61VVVQ6pKZU06IM7hvQtfrRo6FetlXavUjSJ5iVx5cI9lXcgeBpwWVpi",
	"VchOJaGWIC5Q36He6VUbBcZbBejNqpC9UTRXVqY7/AwBWRNIRcHCmTmXSwmWcqX5Z0yPkgSN2eHcNgzA",
	"WzIXcE2FD/coTbV77UjWqkRNvM5Dwmnp/uM9FKVweT3J4QN0iKpCligrSW9ZH4PMBKRo8j6XUhkCcZOo",
	"FDfdRuP4WZ+DIY1IN7CG2/bZD86Ay+DCG3Xdq9UbdfseE8+aT9k0js+1uhVYdBNQoDGQeXg9aBwrGyim",
	"cRyulc0l7Y/XQLgkzFD3I5kjJbmvKblQbxstdvG0Qt/TuGAz9r9oXaVRw2n0SGgVsgb9CuJ+3AG0WWaP",
	"qO8HCko+cOxkKAd4TxoGBJk/3KsfyFca4f9Hhz4qLICLTVpcJ/ileXSVx1r5qc17eObmBhLid5vI6w7S",
	"GN8qJRCks64r/ssJmVsh3jg7J7tcyS3BxaODuPljISu4fI0ycz1jNOqBp5XY8k+sIVX4VH6F6lZgOvQu",
	"uDZ08xjQev+XKpebwPZ7cAnodT5R+JRvH8rL0hHsJNm0wn+aGn+wLp7K4X8l/fOU9Ppac1VjDVeRO3LC",
	"FanNzo8I23m47tOLQf1vVUgOJj8HYz4pnW5utzeGvdF4b3nybP7cfH49v3h1H5+/+i19m714ZYfDYa/e",
	"tvaYTmM8nMTxAMfPbweTUToZwLPRwWAyOTiYTieTRid/p1vpT/496G5QmFjNaXmxvooeI2jUR9Yd+sBu",
	"/dP8kZSXv79jzcXVx+5X12flRCXzl3kuF6p7Ez46Pw0WSgdOnkEBEjIsUFLAZQAyUFJwiUGZgy4gWbKQ",
	"CZ5g07Ib/s5O37nAiZMP15VrcLbe6Oj8lIXsDrWpD4yH8XDUraqCp6nAT6BdeV+xs9bjdcfYC6mAsuSy",
	"rkKvjl2yqTXoUqBKlFByNmP7w3gYN3rzO0QuASZ6qKe0qk6UQMJuyk78+4ByDITKMnQTj8+fKzrXo8AZ",
	"ujmw2cKl5Hjp62C9nK52ai23x8mrftWuTaJm3Kyutya1cTzpmZesH3MWVohlUONKPeq+TjGJR7uqZnVS",
	"tGvaaqvYh9HW79W1g2tsUYAbjB6T6eWXAvkxyrfWK98xDbuuQpYhdQPy00EAtasTtysIrhwVXGbBatze",
	"ZGTRnil6SZn3WHwvXmI/QCpJKH1EUJaCJ/7s6L1xYT20fg74YtPqnY18oW+m6cI2461jNX6a1e0x3/tN",
	"nvbbHNerkE2/5rS+nwj+lH5eINUK2GK9K6LS9oiovow+pSLfIbv1HgYEH9AEJWjiIALrN+tIzq4uvDs1",
	"d9ln8g2i8/wdq3T53fTWnXyqzUuf+wauOoIf/yUAdqu9S6N3S4N2+/u2WviWzvijquLrZN1TJvUp7tRa",
	"dFaL5hIxiyKhEhC5MjQ7jA/jCEoe3Y1YdV39EQAA//+5Prt9FhUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
