openapi: 3.0.0

info:
    title: User Auth Management API
    description: API for user auth management in an online pharmacy
    version: 0.0.1
    license:
        name: MIT
    x-oapi-codegen-middlewares:
        - Middlewares
    x-oapi-codegen-type-mappings:
        uuid: github.com/google/uuid.UUID

servers:
    - url: http://localhost:8080/api/v1


paths:

    /auth/signup:

        # POST /api/v1/auth/signup
        post:
            summary: Create/Sign Up a new user.
            description: Register a new user with an email and password
            operationId: userSignUpHandler
            tags:
                - user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SignUpRequest'
            responses:
                "201":
                    description: User created Successfully. Please verify.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SignUpResponse'
                "400":
                    $ref: '#/components/responses/BadRequestError'
                "500":
                    $ref: '#/components/responses/InternalServerError'



    /auth/login:

        # POST /api/v1/auth/login
        post:
            summary: Log in a user using email and password
            description: log in a user using email and password
            operationID: logInUser
            tags:
                - auth
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SignInRequest'
            responses:
                "200":
                    description: Successful login
                    headers:
                        Set-Cookie:
                            description: Refresh token cookie
                            schema:
                                type: string
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SignInResponse'
                "400":
                    $ref: '#/components/responses/BadRequestError'
                "401":
                    $ref: '#/components/responses/UnauthorizedAccessError'
                "404":
                    $ref: '#/components/responses/NotFoundError'
                "500":
                    $ref: '#/components/responses/InternalServerError'

    /auth/logout:

        # POST /api/v1/auth/logout
        post:
            summary: user logout
            description: logs out the authenticated user by invalidating the refresh token
            tags:
                - auth
            security:
                - BearerAuth: []
            responses:
                "200":
                    description: logout successfully
                    headers:
                        Set-Cookie:
                            description: invalided refresh token cookie
                            schema:
                                type: string
                    content:
                        application/json:
                            schema:
                                type: string
                "401":
                    $ref: '#/components/responses/UnauthorizedAccessError'
                "500":
                    $ref: '#/components/responses/InternalServerError'


    /auth/verify:

        # GET /api/v1/auth/verify?token=%s
        get:
            summary: Verify a user with a confirmation token
            description: After sign up, users go through verification process via token
            operationID: verifySignedUpUser
            tags:
                - auth
            parameters:
                - in: query
                  name: token
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: successfully verified
                "401":
                    $ref: '#/components/responses/UnauthorizedAccessError'
                "500":
                    $ref: '#/components/responses/InternalServerError'

    /auth/reset:

        # POST /api/v1/auth/reset
        post:
            summary: Request for password update for the user
            description: if a user forget his/her password, they can request for password reset
            operationID: requestPasswordReset
            tags:
                - auth
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RequestPasswordReset'
            responses:
                "202":
                    description: status accepted, please check email
                    type: string
                "400":
                    $ref: '#/components/responses/BadRequestError'
                "401":
                    $ref: '#/components/responses/UnauthorizedAccessError'
                "404":
                    $ref: '#/components/responses/NotFoundError'
                "500":
                    $ref: '#/components/responses/InternalServerError'


        # PUT /api/v1/auth/reset
        put:
            summary: update password via verify token for the user
            description: if a user request for password reset, can update via this endpoint
            operationID: updatePasswordReset
            tags:
                - auth
            parameters:
                - in: query
                  name: token
                  required: true
                  schema:
                    type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdatePasswordRequest'
            responses:
                "202":
                    description: password updated
                    type: string
                "400":
                    $ref: '#/components/responses/BadRequestError'
                "401":
                    $ref: '#/components/responses/UnauthorizedAccessError'
                "500":
                    $ref: '#/components/responses/InternalServerError'

components:

    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

    responses:
        InternalServerError:
            description: Internal server error

        BadRequestError:
            description: Invalid input, bad request

        UnauthorizedAccessError:
            description: Unauthorized access

        NotFoundError:
            description: status not found

    schemas:

        # ==================== AUTH ========================

        SignUpRequest:
            type: object
            required:
                - email
                - password
            properties:
                email:
                    type: string
                    format: email
                    example: 'user@example.com'
                password:
                    type: string
                    format: password
                    minLength: 8
                    example: "SecureP@ss123"

        SignUpResponse:
            type: object
            properties:
                user_id:
                    type: string
                    format: googleuuid
                    example: '550e8400-e29b-41d4-a716-446655440000'
                    x-go-type: googleuuid.UUID
                    x-go-type-import:
                        path: github.com/google/uuid
                        name: googleuuid

        SignInRequest:
            type: object
            properties:
                email:
                    type: string
                    format: email
                    example: 'user@example.com'
                password:
                    type: string
                    format: password
                    minLength: 8
                    example: 'SecureP@ss123'
            required:
                - email
                - password

        SignInResponse:
            type: object
            required:
                - access_token
            properties:
                access_token:
                    type: string
                    description: JWT access token

        RequestPasswordReset:
            type: object
            required:
                - email
            properties:
                email:
                    type: string
                    format: email
                    example: 'user@example.com'

        UpdatePasswordRequest:
            type: object
            required:
                - password
            properties:
                password:
                    type: string
                    format: password
                    minLength: 8
                    example: 'SecureP@ss123'
