package db

import (
	"time"

	"github.com/google/uuid"
)

// Medicine represents the medicine entity stored in the database
// @Description Medicine entity contains details about a medicine
type Medicine struct {
	ID           uuid.UUID `json:"id" example:"550e8400-e29b-41d4-a716-446655440000" format:"uuid"` // Unique ID of the user - auto generated by the database
	Name         string    `json:"name" example:"Paracetamol"`                                      // Medicine Name
	Description  string    `json:"description" example:"Pain reliever"`                             // Medicine Description
	Dosage       string    `json:"dosage" example:"500mg"`                                          // Medicine Dosage
	Manufacturer string    `json:"manufacturer" example:"XZY Pharma"`                               // Medicine Manufacturer
	Price        int32     `json:"price" example:"50" format:"int32"`                               // Medicine price
	Stock        int32     `json:"stock" example:"75" format:"int32"`                               // Medicine stock
	Created_at   time.Time `json:"created_at"`                                                      // Medicine creation time - auto-generated by the database
	Updated_at   time.Time `json:"updated_at"`                                                      // Medicine update time - auto-generated by the database
}
