package models

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Medicine represents the medicine entity stored in the database
// @Description Medicine entity contains details about a medicine
type Medicine struct {
	// Unique ID of the user - auto generated by the database
	ID uuid.UUID `json:"id"`
	// Medicine Name
	Name string `json:"name"`
	// Medicine Description
	Description string `json:"description"`
	// Medicine Dosage
	Dosage string `json:"dosage"`
	// Medicine Manufacturer
	Manufacturer string `json:"manufacturer"`
	// Medicine Price
	Price int32 `json:"price"`
	// Medicine Quantity
	Stock int32 `json:"stock"`
	// Medicine creation time - auto-generated by the database
	Created_at time.Time `json:"created_at"`
	// Medicine update time - auto-generated by the database
	Updated_at time.Time `json:"updated_at"`
}

// CreateMedicineDTO represents the request body required for creating a new medicine
// @Description DTO for creating a new medicine
type CreateMedicineDTO struct {
	Name         string `json:"name" binding:"required"`
	Description  string `json:"description" binding:"required"`
	Dosage       string `json:"dosage" binding:"required"`
	Manufacturer string `json:"manufacturer" binding:"required"`
	Price        int32  `json:"price" binding:"required,min=0"`
	Stock        int32  `json:"stock" binding:"required,min=0"`
}

// UpdateMedicineDTO represents the request body required for updating a medicine
// @Description DTO for updating a medicine information
type UpdateMedicineDTO struct {
	Name         string `json:"name,omitempty"`
	Description  string `json:"description,omitempty"`
	Dosage       string `json:"dosage,omitempty"`
	Manufacturer string `json:"manufacturer,omitempty"`
	Price        *int32 `json:"price,omitempty"`
	Stock        *int32 `json:"stock,omitempty"`
}

// MedicineService defines the business logic interface for medicine management
// @Description Interface for medicine-related business logic
type MedicineService interface {
	CreateMedicine(ctx context.Context, medicine CreateMedicineDTO) (Medicine, error)
	DeleteMedicine(ctx context.Context, medID uuid.UUID) error
	UpdateMedicine(ctx context.Context, medID uuid.UUID, med UpdateMedicineDTO) (Medicine, error)
	GetMedicines(ctx context.Context) ([]Medicine, error)
	GetMedicineByID(ctx context.Context, medID uuid.UUID) (Medicine, error)
}

// MedicineRepository defines the DB operations for medicines
// @Description Interface for medicine database transactions
type MedicineRepository interface {
	Create(ctx context.Context, med Medicine) (Medicine, error)
	Delete(ctx context.Context, id uuid.UUID) error
	Update(ctx context.Context, med Medicine) (Medicine, error)
	FindByID(ctx context.Context, id uuid.UUID) (Medicine, error)
	FindAll(ctx context.Context) ([]Medicine, error)
}
